In [ ]:
pip install tensorflow qiskit numpy matplotlib

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 12.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 30.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 12.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 3.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.4/39.4 MB 9.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.5/107.5 kB 13.7 MB/s eta 0:00:00


In [ ]:
import tensorflow as tf
from tensorflow.keras import layers

def build_critic(img_shape):
    model = tf.keras.Sequential()
    model.add(layers.Flatten(input_shape=img_shape))
    model.add(layers.Dense(512))
    model.add(layers.LeakyReLU(alpha=0.2))
    model.add(layers.Dense(512))
    model.add(layers.LeakyReLU(alpha=0.2))
    model.add(layers.Dense(1))
    return model

In [ ]:
pip install qiskit-aer

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 47.9 MB/s eta 0:00:00


In [ ]:
pip uninstall qiskit qiskit-aer qiskit-terra -y


Found existing installation: qiskit 1.1.0
Uninstalling qiskit-1.1.0:
  Successfully uninstalled qiskit-1.1.0
Found existing installation: qiskit-aer 0.14.2
Uninstalling qiskit-aer-0.14.2:
  Successfully uninstalled qiskit-aer-0.14.2


In [ ]:
pip install qiskit qiskit-aer


  Using cached qiskit-1.1.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
  Using cached qiskit_aer-0.14.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)


In [ ]:
import qiskit
print(qiskit.__version__)


1.1.0


In [ ]:
pip uninstall qiskit qiskit-aer qiskit-terra -y


Found existing installation: qiskit 1.1.0
Uninstalling qiskit-1.1.0:
  Successfully uninstalled qiskit-1.1.0
Found existing installation: qiskit-aer 0.14.2
Uninstalling qiskit-aer-0.14.2:
  Successfully uninstalled qiskit-aer-0.14.2


In [ ]:
pip install qiskit qiskit-aer


  Using cached qiskit-1.1.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
  Using cached qiskit_aer-0.14.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)


In [ ]:
# Install the necessary package
!pip install pennylane

# Import necessary libraries
import tensorflow as tf
from tensorflow.keras import layers
import pennylane as qml
from pennylane import numpy as np

# Initialize quantum generator parameters
n_qubits = 4
n_layers = 3

# Generate random parameters for the quantum generator
generator_params = np.random.normal(size=(n_layers, n_qubits, 3))

print("Initialized Quantum Generator Parameters:")
print(generator_params)

# Define Wasserstein loss function
def wasserstein_loss(y_true, y_pred):
    return tf.reduce_mean(y_true * y_pred)

# Build and compile the discriminator (critic)
def build_critic(img_shape):
    model = tf.keras.Sequential()
    model.add(layers.Conv2D(64, kernel_size=3, strides=2, input_shape=img_shape, padding="same"))
    model.add(layers.LeakyReLU(alpha=0.2))
    model.add(layers.Conv2D(128, kernel_size=3, strides=2, padding="same"))
    model.add(layers.LeakyReLU(alpha=0.2))
    model.add(layers.Flatten())
    model.add(layers.Dense(1))
    return model

# Define the shape of the input images
img_shape = (28, 28, 1)

# Build the discriminator model
critic = build_critic(img_shape)

# Compile the discriminator model
critic.compile(optimizer=tf.keras.optimizers.Adam(0.0002, 0.5), loss=wasserstein_loss)

print("Discriminator Model Summary:")
critic.summary()


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 10.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 19.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 6.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 51.1 MB/s eta 0:00:00
Initialized Quantum Generator Parameters:
[[[ 1.57389788  0.51457711  0.61756031]
  [ 0.69340404  1.187808    1.14409494]
  [-0.61087586  0.8076829  -0.60225352]
  [-0.30756206 -1.68493856 -2.16526833]]

 [[-2.80270162 -0.87731535 -0.61373228]
  [-0.35615084 -1.03617506 -0.31184317]
  [-0.31563727 -1.51824286 -0.33255271]
  [-1.24963332  0.57381953 -0.13114736]]

 [[-0.12023885  2.24568792  0.38694774]
  [ 1.02608737  0.92640109  0.06062096]
  [-0.48662497 -0.60013013  0.71706136]
  [-1.16622505 -0.20600394  0.49598812]]]
Discriminator Model Summary:
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Sh

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers
import pennylane as qml
from pennylane import numpy as np

# Define the quantum device
n_qubits = 4
n_layers = 3
latent_dim = n_qubits  # Match the latent dimension to the number of qubits
dev = qml.device('default.qubit', wires=n_qubits)

# Define the quantum generator circuit
def quantum_circuit(params, latent_vector):
    qml.AngleEmbedding(latent_vector, wires=range(n_qubits))
    qml.StronglyEntanglingLayers(params, wires=range(n_qubits))
    return [qml.expval(qml.PauliZ(i)) for i in range(n_qubits)]

@qml.qnode(dev, interface="tf")
def quantum_generator(params, latent_vector):
    return qml.math.stack(quantum_circuit(params, latent_vector))

# Classical post-processing layer to reshape quantum generator output
class QuantumGenerator(tf.keras.layers.Layer):
    def __init__(self, params):
        super(QuantumGenerator, self).__init__()
        self.params = params
        self.dense = layers.Dense(28 * 28 * 1, activation='tanh')

    def call(self, inputs):
        gen_output = tf.map_fn(lambda x: quantum_generator(self.params, x), inputs, dtype=tf.float32)
        reshaped_output = self.dense(gen_output)
        reshaped_output = tf.reshape(reshaped_output, (-1, 28, 28, 1))
        return reshaped_output

# Define the classical discriminator (critic)
def build_critic(img_shape):
    model = tf.keras.Sequential()
    model.add(layers.Conv2D(64, kernel_size=3, strides=2, input_shape=img_shape, padding="same"))
    model.add(layers.LeakyReLU(alpha=0.2))
    model.add(layers.Conv2D(128, kernel_size=3, strides=2, padding="same"))
    model.add(layers.LeakyReLU(alpha=0.2))
    model.add(layers.Flatten())
    model.add(layers.Dense(1))
    return model

# Define Wasserstein loss and gradient penalty
def wasserstein_loss(y_true, y_pred):
    return tf.reduce_mean(y_true * y_pred)

def gradient_penalty(critic, real_images, fake_images, batch_size):
    alpha = tf.random.normal([batch_size, 1, 1, 1])
    interpolated = alpha * real_images + (1 - alpha) * fake_images
    with tf.GradientTape() as tape:
        tape.watch(interpolated)
        validity = critic(interpolated, training=True)
    gradients = tape.gradient(validity, [interpolated])[0]
    gradients = tf.reshape(gradients, [batch_size, -1])
    penalty = tf.reduce_mean((tf.norm(gradients, axis=1) - 1.0) ** 2)
    return penalty

# Training function
def train(generator, critic, real_images, epochs, batch_size, latent_dim, critic_iterations, lambda_gp):
    for epoch in range(epochs):
        for _ in range(critic_iterations):
            idx = np.random.randint(0, real_images.shape[0], batch_size)
            real_imgs = real_images[idx]

            noise = np.random.normal(0, 1, (batch_size, latent_dim))
            gen_imgs = generator(noise)

            with tf.GradientTape() as tape:
                real_validity = critic(real_imgs, training=True)
                fake_validity = critic(gen_imgs, training=True)
                gp = gradient_penalty(critic, real_imgs, gen_imgs, batch_size)
                d_loss = tf.reduce_mean(fake_validity) - tf.reduce_mean(real_validity) + lambda_gp * gp

            grads = tape.gradient(d_loss, critic.trainable_variables)
            critic.optimizer.apply_gradients(zip(grads, critic.trainable_variables))

        noise = np.random.normal(0, 1, (batch_size, latent_dim))
        misleading_labels = -tf.ones((batch_size, 1))

        with tf.GradientTape() as tape:
            gen_imgs = generator(noise)
            g_loss = wasserstein_loss(misleading_labels, critic(gen_imgs, training=True))

        grads = tape.gradient(g_loss, generator.trainable_variables)
        generator.optimizer.apply_gradients(zip(grads, generator.trainable_variables))

        print(f'Epoch {epoch}/{epochs}, d_loss={d_loss.numpy()}, g_loss={g_loss.numpy()}')

# Load datasets and preprocess
mnist = tf.keras.datasets.mnist
(train_images_mnist, _), (test_images_mnist, _) = mnist.load_data()
train_images_mnist = train_images_mnist / 255.0
train_images_mnist = train_images_mnist[..., tf.newaxis].astype("float32")

# Initialize critic and generator parameters
img_shape = (28, 28, 1)
critic = build_critic(img_shape)
critic.compile(optimizer=tf.keras.optimizers.Adam(0.0002, 0.5), loss=wasserstein_loss)

generator_params = np.random.normal(size=(n_layers, n_qubits, 3))
quantum_generator_layer = QuantumGenerator(generator_params)

# Build and compile the generator model
generator_input = tf.keras.Input(shape=(latent_dim,))
generator_output = quantum_generator_layer(generator_input)
generator_model = tf.keras.Model(generator_input, generator_output)
generator_model.compile(optimizer=tf.keras.optimizers.Adam(0.0002, 0.5))

# Train the PQWGAN on MNIST dataset
train(generator_model, critic, train_images_mnist, epochs=10000, batch_size=32, latent_dim=latent_dim, critic_iterations=5, lambda_gp=10)


NotImplementedError: Exception encountered when calling layer "quantum_generator_6" (type QuantumGenerator).

in user code:

    File "<ipython-input-15-d96aa3125dfb>", line 30, in call  *
        gen_output = tf.map_fn(lambda x: quantum_generator(self.params, x), inputs, dtype=tf.float32)
    File "/usr/local/lib/python3.10/dist-packages/pennylane/workflow/qnode.py", line 1098, in __call__  *
        res = self._execution_component(args, kwargs, override_shots=override_shots)
    File "/usr/local/lib/python3.10/dist-packages/pennylane/workflow/qnode.py", line 1074, in _execution_component  *
        res, self._qfunc_output, self._tape.shots.has_partitioned_shots
    File "/usr/local/lib/python3.10/dist-packages/pennylane/workflow/qnode.py", line 101, in _to_qfunc_output_type  *
        return type(qfunc_output)(results)
    File "/usr/local/lib/python3.10/dist-packages/pennylane/numpy/tensor.py", line 111, in __new__  **
        obj = asarray(input_array, *args, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/autograd/tracer.py", line 48, in f_wrapped
        return f_raw(*args, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/pennylane/numpy/tensor.py", line 36, in asarray
        return _np.array(vals, *args, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/autograd/numpy/numpy_wrapper.py", line 58, in array
        return array_from_args(args, kwargs, *map(array, A))
    File "/usr/local/lib/python3.10/dist-packages/autograd/numpy/numpy_wrapper.py", line 60, in array
        return _array_from_scalar_or_array(args, kwargs, A)
    File "/usr/local/lib/python3.10/dist-packages/autograd/tracer.py", line 48, in f_wrapped
        return f_raw(*args, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/autograd/numpy/numpy_wrapper.py", line 73, in _array_from_scalar_or_array
        return _np.array(scalar, *array_args, **array_kwargs)

    NotImplementedError: Cannot convert a symbolic tf.Tensor (quantum_generator_6/map/while/Tensordot:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported.


Call arguments received by layer "quantum_generator_6" (type QuantumGenerator):
  • inputs=tf.Tensor(shape=(None, 4), dtype=float32)